@extends('layouts.base', ['area'=>'client'])
@section('title','Cobrança — AlugaPro')
@section('content')
@php($staticPayments = $charge->pixPayments->where('provider','local_emv_static'))
@php($payment = session('payment_id') ? $staticPayments->firstWhere('id',session('payment_id')) : $staticPayments->where('status','active')->where('expires_at','>',now())->sortByDesc('id')->first())
<div class="page-head"><div><a style="color:var(--blue);font-weight:700" href="{{ route('client.dashboard') }}">← Voltar</a><h1 style="margin-top:8px">{{ $charge->type==='solar'?'Energia solar':'Aluguel' }}</h1><p>{{ $charge->lease->property->title }} · {{ $charge->reference_month->translatedFormat('F/Y') }}</p></div><x-status :value="$charge->status"/></div>
<div class="grid-2"><section class="card"><h2>Resumo da cobrança</h2><div class="money-breakdown"><div class="money-line"><span>Valor original</span><strong>R$ {{ number_format($payable['original'],2,',','.') }}</strong></div>@if($payable['days_late']>0)<div class="money-line"><span>Multa ({{ config('business.late_fee_percent') }}%)</span><strong>R$ {{ number_format($payable['fine'],2,',','.') }}</strong></div><div class="money-line"><span>Juros ({{ $payable['days_late'] }} dias)</span><strong>R$ {{ number_format($payable['interest'],2,',','.') }}</strong></div>@endif<div class="money-line total"><span>Total</span><strong>R$ {{ number_format($payable['total'],2,',','.') }}</strong></div></div><p style="color:var(--muted)">Vencimento: {{ $charge->due_date->format('d/m/Y') }}</p>@if($charge->status==='open'&&!$payment)<form method="post" action="{{ route('client.pix',$charge) }}">@csrf<button class="btn btn-block"><x-icon name="money"/> Gerar Pix copia e cola</button></form>@endif</section>
<section class="card">@if($payment)<h2>Pix copia e cola</h2><div class="alert alert-success"><x-icon name="check"/> Código estático gerado. Disponível nesta tela até {{ $payment->expires_at->format('H:i') }}.</div><textarea id="pix-code" class="pix-code" readonly>{{ $payment->br_code }}</textarea><button class="btn btn-block" style="margin-top:12px" data-copy="#pix-code">Copiar código Pix</button><small style="display:block;color:var(--muted);margin-top:10px">Após o pagamento, a confirmação depende do webhook do provedor Pix configurado.</small>@elseif($charge->status==='paid')<div class="empty"><div class="metric-icon"><x-icon name="check"/></div><h2>Pagamento confirmado</h2><p>Pago em {{ $charge->paid_at?->format('d/m/Y H:i') }}.</p></div>@else<div class="empty"><div class="metric-icon"><x-icon name="money"/></div><h2>Pague pelo seu banco</h2><p>Gere um código Pix estático para copiar e colar.</p></div>@endif</section></div>
@endsection
