@extends('layouts.base', ['area'=>'client'])
@section('title','Minha área — AlugaPro')
@section('content')
<section class="hero" style="padding:30px;margin-bottom:22px"><div class="hero-copy"><small>Minha área</small><h1 style="font-size:31px">Tudo certo por aqui, {{ explode(' ',$client->name)[0] }}.</h1><p>Acompanhe contratos, pagamentos e consumo de energia.</p></div><div class="hero-art"><x-icon name="home" size="90"/></div></section>
@if($client->leases->isEmpty())<div class="card empty"><div class="metric-icon"><x-icon name="key"/></div><h2>Sua proposta está em análise</h2><p>Assim que o responsável avançar, o contrato aparecerá aqui.</p></div>@endif
@foreach($client->leases as $lease)<section class="card" style="margin-bottom:20px"><div class="page-head"><div><small style="color:var(--muted)">Seu imóvel</small><h2 style="margin:3px 0">{{ $lease->property->title }}</h2><p>{{ $lease->property->neighborhood }}, {{ $lease->property->city }}</p></div><x-status :value="$lease->status"/></div><div class="grid-3"><div><small style="color:var(--muted)">Aluguel</small><strong style="display:block;font-size:18px">R$ {{ number_format((float)$lease->rent_amount,2,',','.') }}</strong></div><div><small style="color:var(--muted)">Vencimento</small><strong style="display:block;font-size:18px">Dia {{ $lease->due_day }}</strong></div><div><small style="color:var(--muted)">Contrato</small><strong style="display:block;font-size:18px">{{ $lease->contract?->status==='signed'?'Assinado':'Em andamento' }}</strong></div></div><div class="form-actions" style="position:static"><a class="btn" href="{{ route('client.lease',$lease) }}">Ver detalhes <x-icon name="arrow"/></a></div></section>
<section class="card" id="cobrancas" style="margin-bottom:20px"><h2>Pagamentos</h2>@forelse($lease->charges->take(6) as $charge)<a class="list-row" href="{{ route('client.charge',$charge) }}"><span class="metric-icon"><x-icon name="{{ $charge->type==='solar'?'sun':'home' }}"/></span><span class="list-row-main"><strong>{{ $charge->type==='solar'?'Energia solar':'Aluguel' }} · {{ $charge->reference_month->translatedFormat('M/Y') }}</strong><small>Vence em {{ $charge->due_date->format('d/m/Y') }}</small></span><span class="amount">R$ {{ number_format((float)$charge->amount,2,',','.') }}</span><x-status :value="$charge->status"/></a>@empty<div class="empty">Nenhuma cobrança gerada ainda.</div>@endforelse</section>
@if($lease->contract)<section class="card" id="contratos"><div class="list-row"><span class="metric-icon"><x-icon name="file"/></span><span class="list-row-main"><strong>Contrato de locação</strong><small>{{ $lease->contract->status==='signed'?'Assinado digitalmente':'Aguardando assinaturas' }}</small></span><a class="btn btn-sm" href="{{ route('contracts.show',$lease->contract) }}">Abrir</a></div></section>@endif
@endforeach
@endsection
